"""tk-studio project knowledge base — kb/ with a generated ranked index (ST-2.4, AD-3).

Project knowledge lives at {project-root}/kb/ as agent-first markdown on the
project's VCS. `index.md` is the agent's entry point: an llms.txt-style ranked
list of links with one-line descriptions, fully generated — ranking comes from
each file's frontmatter, never from hand-reordering the index.

Per-file metadata (all optional, YAML frontmatter):
  title:        display title   (fallback: first '# ' heading, then filename)
  description:  one-liner       (fallback: first body paragraph line, truncated)
  rank:         number, lower sorts first (default 100; ties break by path)

Index generation is deterministic (one line per file, stable order, LF,
atomic write) so reruns produce review-friendly diffs. A pre-existing
index.md without the generated marker is refused, never overwritten —
brownfield content is surfaced, not clobbered (AD-3 posture).

CLI:
  uv run kb.py standup --directory DIR    # create kb/ + index.md (idempotent)
  uv run kb.py index --directory DIR      # regenerate index.md

Exit codes: 0 ok; 2 refusal; 1 unexpected failure.
Stdlib-only (NFR9); never prompts (AD-11).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

import miniyaml

GENERATED_MARKER = "<!-- generated by tk-studio kb.py — edit file frontmatter, not this index -->"
DEFAULT_RANK = 100
DESCRIPTION_LIMIT = 120


class KbError(Exception):
    """Refusal or invalid kb state; message is safe to surface."""


def kb_dir(project_root: Path) -> Path:
    return Path(project_root) / "kb"


def index_path(project_root: Path) -> Path:
    return kb_dir(project_root) / "index.md"


# ------------------------------------------------------------- file metadata

def _parse_frontmatter(text: str) -> tuple[dict, str, str | None]:
    """(frontmatter, body, error). Absent frontmatter → ({}, whole text,
    None); broken frontmatter → ({}, body, the parse error) — the caller
    surfaces it loudly (ST-059: swallowing it left a mis-indexed file with
    no signal)."""
    if text.startswith("---\n") or text.startswith("---\r\n"):
        parts = re.split(r"^---\s*$", text, maxsplit=2, flags=re.MULTILINE)
        if len(parts) >= 3:
            try:
                return miniyaml.loads(parts[1]) or {}, parts[2], None
            except miniyaml.MiniYamlError as exc:
                return {}, parts[2], str(exc)
    return {}, text, None


def _first_heading(body: str) -> str | None:
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def _first_paragraph_line(body: str) -> str | None:
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "---", "```", "<!--", "|", ">")):
            continue
        return stripped
    return None


def _entry_for(kb_root: Path, path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    front, body, error = _parse_frontmatter(text)
    title = str(front.get("title") or _first_heading(body) or path.stem)
    description = str(front.get("description") or _first_paragraph_line(body) or "")
    description = " ".join(description.split())
    if len(description) > DESCRIPTION_LIMIT:
        description = description[: DESCRIPTION_LIMIT - 1].rstrip() + "…"
    rank = front.get("rank")
    if not isinstance(rank, (int, float)) or isinstance(rank, bool):
        rank = DEFAULT_RANK
    entry = {
        "path": path.relative_to(kb_root).as_posix(),
        "title": title,
        "description": description,
        "rank": rank,
    }
    if error:
        entry["warning"] = (f"{entry['path']}: frontmatter ignored "
                            f"(indexed on fallbacks) — {error}")
    return entry


def scan(project_root: Path) -> list[dict]:
    """All kb markdown files (index.md excluded), ranked then path-ordered."""
    root = kb_dir(project_root)
    if not root.is_dir():
        raise KbError(f"{root} does not exist — run kb standup first")
    entries = [
        _entry_for(root, p)
        for p in sorted(root.rglob("*.md"))
        if p.resolve() != index_path(project_root).resolve()
    ]
    entries.sort(key=lambda e: (e["rank"], e["path"]))
    return entries


# ----------------------------------------------------------------- rendering

def render_index(project_name: str, entries: list[dict]) -> str:
    lines = [
        f"# {project_name} — knowledge base",
        "",
        GENERATED_MARKER,
        "",
        "> Agent entry point for project knowledge (AD-3). Ranked: lower",
        "> frontmatter `rank` sorts first (default 100), ties by path.",
        "> Regenerate: `uv run <plugin>/lib/kb.py index --directory <project-root>`",
        "",
    ]
    if entries:
        lines.extend(
            f"- [{e['title']}]({e['path']})" + (f" — {e['description']}" if e["description"] else "")
            for e in entries
        )
    else:
        lines.append("_No knowledge files yet — add markdown files under `kb/`, then regenerate._")
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, content: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=path.name, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def generate_index(project_root: Path) -> dict:
    """Regenerate index.md from current kb files. Refuses a foreign index."""
    project_root = Path(project_root).resolve()
    target = index_path(project_root)
    if target.exists() and GENERATED_MARKER not in target.read_text(
            encoding="utf-8", errors="replace"):
        raise KbError(
            f"{target} exists but was not generated by kb.py — refusing to "
            f"overwrite; move its content into kb/ files (or delete it) and rerun")
    entries = scan(project_root)
    content = render_index(project_root.name, entries)
    changed = not target.exists() or target.read_text(encoding="utf-8") != content
    if changed:
        _atomic_write(target, content)
    warnings = [e["warning"] for e in entries if "warning" in e]
    return {"index": str(target), "entries": len(entries), "changed": changed,
            "warnings": warnings}


def standup_kb(project_root: Path) -> dict:
    """Create kb/ and its index; idempotent, preservation-first."""
    project_root = Path(project_root).resolve()
    if not project_root.is_dir():
        raise KbError(f"project root {project_root} is not a directory")
    root = kb_dir(project_root)
    created = []
    if not root.is_dir():
        root.mkdir(parents=True)
        created.append("kb/")
    result = generate_index(project_root)
    if result["changed"] and "kb/" in created:
        created.append("kb/index.md")
    return {"project_root": str(project_root), "created": created, **result}


# --------------------------------------------------------------------- CLI

def main(argv: list[str] | None = None) -> int:
    # Headless output must survive a cp1252 Windows console: payloads are
    # arbitrary unicode and must always print (AD-11).
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = argparse.ArgumentParser(description="tk-studio knowledge base")
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("standup", "index"):
        cmd = sub.add_parser(name)
        cmd.add_argument("--directory", required=True, help="project root")
    args = parser.parse_args(argv)

    try:
        if args.command == "standup":
            result = standup_kb(Path(args.directory))
        else:
            result = generate_index(Path(args.directory))
        print(json.dumps({"ok": True, "mutated": result["changed"], **result},
                         ensure_ascii=False, indent=2))
        return 0
    except KbError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False))
        return 2


if __name__ == "__main__":
    sys.exit(main())
