"""install_base.py (tk-studio-install) — a same-pin install is a no-op.

The 2026-09-26 report: installing at exactly the committed bmad.lock pins
left the tree dirty — re-stamped manifest, re-serialized config values,
line-ending rewrites, *.bak drops — because only base-update normalized the
upstream reinstall's churn. These drive main() end to end over a temp git
repo, with a fake upstream installer that reproduces that churn signature,
and pin the invocation shape the lock renders.
"""
from __future__ import annotations

import contextlib
import io
import json
import os
import re
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

PLUGIN_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PLUGIN_ROOT / "lib"))
sys.path.insert(0, str(PLUGIN_ROOT / "skills" / "tk-studio-install" / "scripts"))

import bmadlock  # noqa: E402
import install_base  # noqa: E402

LOCK = bmadlock.parse_lock(install_base.LOCK_PATH)
PINS = bmadlock.lock_pins(LOCK)

CONFIG_OLD = b"""# GDS Module Configuration
# Generated by BMAD installer
# Version: 6.10.0
# Date: 2026-07-26T23:44:12.202Z

primary_platform:
  - unity
  - unreal
user_name: Tim
output_folder: _bmad-output
"""

# the live 6.11.0 reinstall signature: header re-stamped, the list
# re-serialized as a JSON string, a comment block inserted
CONFIG_CHURN = b"""# GDS Module Configuration
# Generated by BMAD installer
# Version: 6.11.0
# Date: 2026-09-27T19:56:20.618Z

primary_platform: '["unity", "unreal"]'

# Core Configuration Values
user_name: Tim
output_folder: _bmad-output
"""

TOOL_COMMITTED = b"print('hi')\r\n"


def _manifest(stamp: str) -> str:
    lines = ["installation:", f"  version: {PINS['core']}",
             f"  lastUpdated: {stamp}", "modules:"]
    for name, version in PINS.items():
        lines += [f"  - name: {name}", f"    version: {version}",
                  f"    lastUpdated: {stamp}"]
    return "\n".join(lines + ["ides:", "  - claude-code"]) + "\n"


# Stands in for `npx bmad-method@<pin> install`: runs in the project root
# (install_base's cwd) and rewrites what the real reinstall rewrites.
FAKE_INSTALLER = r'''
import re, sys
from pathlib import Path
args = set(sys.argv[1:])
bmad = Path("_bmad")
m = bmad / "_config" / "manifest.yaml"
text = re.sub(r"(lastUpdated:).*", r"\1 2026-09-27T19:56:20.801Z", m.read_text())
if "--bad-version" in args:
    text = text.replace("  - name: core\n    version: ", "  - name: core\n    version: 0.0.0-", 1)
m.write_bytes(text.encode())
config = CONFIG_CHURN
if "--real-change" in args:
    config = config.replace(b"output_folder: _bmad-output",
                            b'output_folder: "{project-root}/_bmad-output"')
(bmad / "gds" / "config.yaml").write_bytes(config)
tool = bmad / "scripts" / "tool.py"
(bmad / "scripts" / "tool.py.bak").write_bytes(tool.read_bytes())
tool.write_bytes(b"print('hi')\n")
'''


class InstallBaseTestCase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        base = Path(self._tmp.name)
        self.repo = base / "project"
        self.repo.mkdir()
        fake = base / "fake_installer.py"
        fake.write_text(f"CONFIG_CHURN = {CONFIG_CHURN!r}\n" + FAKE_INSTALLER,
                        encoding="utf-8")
        self.fake = fake
        self._env = mock.patch.dict(os.environ,
                                    {"GIT_CEILING_DIRECTORIES": str(base)})
        self._env.start()
        self._git("init", "-q")
        self._git("config", "core.autocrlf", "false")
        self._git("config", "user.email", "t@t")
        self._git("config", "user.name", "t")
        (self.repo / "_bmad" / "_config").mkdir(parents=True)
        (self.repo / "_bmad" / "gds").mkdir()
        (self.repo / "_bmad" / "scripts").mkdir()
        (self.repo / "_bmad" / "_config" / "manifest.yaml").write_bytes(
            _manifest("2026-08-12T22:00:16.718Z").encode())
        (self.repo / "_bmad" / "gds" / "config.yaml").write_bytes(CONFIG_OLD)
        (self.repo / "_bmad" / "scripts" / "tool.py").write_bytes(TOOL_COMMITTED)
        self._git("add", "-A")
        self._git("commit", "-q", "-m", "installed at the pin")
        # never write a real install-outcome event from a test
        self._emit = mock.patch.object(install_base.ledger, "emit")
        self.emit = self._emit.start()

    def tearDown(self):
        self._emit.stop()
        self._env.stop()
        self._tmp.cleanup()

    def _git(self, *args) -> str:
        return subprocess.run(["git", *args], cwd=str(self.repo), check=True,
                              stdin=subprocess.DEVNULL, capture_output=True,
                              encoding="utf-8").stdout

    def _dirty(self) -> list[str]:
        return sorted(line[3:] for line in
                      self._git("status", "--porcelain", "-uall").splitlines())

    def _install(self, *argv: str, fake_args: tuple[str, ...] = ()) -> tuple[int, dict]:
        cmd = [sys.executable, str(self.fake), *fake_args]
        out = io.StringIO()
        with mock.patch.object(install_base, "build_command", return_value=cmd), \
                contextlib.redirect_stdout(out):
            code = install_base.main(["--directory", str(self.repo), *argv])
        return code, json.loads(out.getvalue())

    def test_same_pin_install_over_committed_tree_is_a_no_op(self):
        code, result = self._install()

        self.assertEqual(code, 0, result)
        self.assertTrue(result["ok"])
        self.assertEqual(result["normalized"], {
            "reverted": 3, "backups_dropped": 1, "remaining": 0,
            "by_class": {"manifest-timestamps-only": 1,
                         "config-values-unchanged": 1,
                         "line-endings-only": 1,
                         "installer-backup-dropped": 1},
        })
        self.assertEqual(self._dirty(), [])
        self.assertEqual(self.emit.call_args.args[0], "install-outcome")
        self.assertEqual(self.emit.call_args.args[1]["outcome"], "success")

    def test_real_upstream_change_stays_and_is_counted(self):
        # the 6.11.0 output_folder template: a real value change — the whole
        # file stays (its list coercion rides along, per D2), never patched
        code, result = self._install(fake_args=("--real-change",))

        self.assertEqual(code, 0, result)
        self.assertEqual(result["normalized"]["remaining"], 1)
        self.assertEqual(self._dirty(), ["_bmad/gds/config.yaml"])
        self.assertIn(b"{project-root}/_bmad-output",
                      (self.repo / "_bmad" / "gds" / "config.yaml").read_bytes())

    def test_paths_dirty_before_the_install_are_preserved(self):
        tool = self.repo / "_bmad" / "scripts" / "tool.py"
        tool.write_bytes(b"print('local edit')\r\n")

        code, result = self._install()

        self.assertEqual(code, 0, result)
        self.assertEqual(result["normalized"]["preserved"], 1)
        # the installer's own write stands; normalization never reverted it
        self.assertEqual(tool.read_bytes(), b"print('hi')\n")
        # its backup holds the local edit — not a committed copy, so it is
        # kept and counted: the operator must see where the edit went
        self.assertEqual(result["normalized"]["remaining"], 1)
        self.assertEqual(self._dirty(), ["_bmad/scripts/tool.py",
                                         "_bmad/scripts/tool.py.bak"])

    def test_no_normalize_leaves_upstream_output(self):
        code, result = self._install("--no-normalize")

        self.assertEqual(code, 0, result)
        self.assertEqual(result["normalized"], {"skipped": "--no-normalize"})
        self.assertEqual(self._dirty(), ["_bmad/_config/manifest.yaml",
                                         "_bmad/gds/config.yaml",
                                         "_bmad/scripts/tool.py",
                                         "_bmad/scripts/tool.py.bak"])

    def test_verify_failure_never_normalizes(self):
        code, result = self._install(fake_args=("--bad-version",))

        self.assertEqual(code, 1)
        self.assertEqual(result["step"], "verify-at-pin")
        self.assertNotIn("normalized", result)
        self.assertIn("_bmad/scripts/tool.py.bak", self._dirty())
        self.assertEqual(self.emit.call_args.args[1]["outcome"], "failure")

    def test_normalization_failure_keeps_the_verified_install(self):
        with mock.patch.object(install_base.bmadchurn, "normalize_churn",
                               side_effect=RuntimeError("git checkout failed")):
            code, result = self._install()

        self.assertEqual(code, 0, result)
        self.assertTrue(result["ok"])
        self.assertIn("git checkout failed", result["normalized"]["error"])
        self.assertIn("git restore", result["normalized"]["recover"])
        self.assertEqual(self.emit.call_args.args[1]["outcome"], "success")

    def test_outside_a_git_top_level_normalization_is_skipped(self):
        (self.repo / ".git").rename(self.repo.parent / "moved.git")

        code, result = self._install()

        self.assertEqual(code, 0, result)
        self.assertEqual(result["normalized"], {"skipped": "not a git work tree"})
        self.assertTrue((self.repo / "_bmad" / "scripts" / "tool.py.bak").exists())

    def test_dry_run_names_the_normalize_plan(self):
        with mock.patch.object(install_base.shutil, "which", return_value="npx"):
            out = io.StringIO()
            with contextlib.redirect_stdout(out):
                code = install_base.main(["--directory", str(self.repo), "--dry-run"])
        result = json.loads(out.getvalue())
        self.assertEqual(code, 0)
        self.assertEqual(result["normalize"],
                         "revert provable churn under _bmad, .claude/skills")
        self.emit.assert_not_called()


class BuildCommandTestCase(unittest.TestCase):
    """The invocation shape the lock renders (PR #57: an existing _bmad
    forces the full update path, the only one that honors --pin)."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.dir = Path(self._tmp.name)
        self._which = mock.patch.object(install_base.shutil, "which",
                                        return_value="npx")
        self._which.start()

    def tearDown(self):
        self._which.stop()
        self._tmp.cleanup()

    def test_fresh_install_pins_every_external_module(self):
        cmd = install_base.build_command(LOCK, self.dir, list(LOCK["modules"]))
        self.assertEqual(cmd[2], f"bmad-method@{PINS['core']}")
        self.assertNotIn("--action", cmd)
        pins = [cmd[i + 1] for i, a in enumerate(cmd) if a == "--pin"]
        external = [m for m, s in LOCK["modules"].items() if s.get("source") == "external"]
        self.assertEqual(pins, [f"{m}={PINS[m]}" for m in external])
        self.assertTrue(all(not re.match(r"bmm=", p) for p in pins))  # built-in

    def test_existing_install_forces_the_full_update_action(self):
        (self.dir / "_bmad").mkdir()
        cmd = install_base.build_command(LOCK, self.dir, list(LOCK["modules"]))
        self.assertEqual(cmd[cmd.index("--action") + 1], "update")


if __name__ == "__main__":
    unittest.main()
