"""lib/bmadchurn.py — the EP-011 churn normalizer (ST-043), shared by
tk-studio-install and tk-studio-base-update.

The equivalence checks are the load-bearing part (D2: revert only what is
provably churn; real changes and unknown churn stay untouched), so they get
the coverage: the four AC-named cases, each additional ruled class from the
live corpus (2026-08-08 full no-op signature ruling), and end-to-end
normalizes over a real temp git repo — including the install-side
guarantees: paths dirty before the install are preserved, and what stays
real is counted.
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

PLUGIN_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PLUGIN_ROOT / "lib"))

import bmadchurn  # noqa: E402

YAML_OLD = b"""# GDS Module Configuration
# Generated by BMAD installer
# Version: 6.10.0
# Date: 2026-07-26T23:44:12.202Z

primary_platform:
  - unity
  - unreal
user_name: Tim
communication_language: English
"""

# same values: list re-serialized as a JSON string, Date comment rewritten,
# keys reordered, a comment header inserted — the live churn signature
YAML_CHURN = b"""# GDS Module Configuration
# Generated by BMAD installer
# Version: 6.10.0
# Date: 2026-08-08T04:44:37.022Z

primary_platform: '["unity", "unreal"]'

# Core Configuration Values
communication_language: English
user_name: Tim
"""


class ChurnClassTestCase(unittest.TestCase):
    # --- AC case 1: endings-only reverted

    def test_endings_only_is_churn(self):
        old = b"line one\r\nline two\r\n"
        new = b"line one\nline two\n"
        self.assertEqual(bmadchurn.churn_class("_bmad/scripts/x.py", old, new),
                         "line-endings-only")

    # --- AC case 2: re-serialization reverted (with the inseparable comment
    # timestamp / key-order churn from the live corpus)

    def test_config_yaml_reserialization_is_churn(self):
        self.assertEqual(
            bmadchurn.churn_class("_bmad/gds/config.yaml", YAML_OLD, YAML_CHURN),
            "config-values-unchanged")

    # --- AC case 3: mixed real change stays untouched

    def test_config_yaml_with_real_value_change_stays(self):
        real = YAML_CHURN.replace(b"user_name: Tim", b"user_name: Bob")
        self.assertIsNone(
            bmadchurn.churn_class("_bmad/gds/config.yaml", YAML_OLD, real))

    # --- AC case 4: unknown churn stays untouched

    def test_unknown_churn_stays(self):
        old = b"# doc\r\nSome instruction text.\r\n"
        new = b"# doc\nSome instruction text, reworded.\n"
        self.assertIsNone(
            bmadchurn.churn_class(".claude/skills/x/SKILL.md", old, new))

    # --- ruled classes beyond the AC-named four (full no-op signature)

    def test_config_toml_list_coercion_is_churn(self):
        old = b'[modules.gds]\nprimary_platform = ["unity", "unreal"]\n'
        new = b'[modules.gds]\nprimary_platform = "[\\"unity\\", \\"unreal\\"]"\n'
        self.assertEqual(bmadchurn.churn_class("_bmad/config.toml", old, new),
                         "config-values-unchanged")

    def test_config_toml_real_change_stays(self):
        old = b'[agents.x]\ndescription = "old"\n'
        new = b'[agents.x]\ndescription = "new"\n'
        self.assertIsNone(bmadchurn.churn_class("_bmad/config.toml", old, new))

    def test_manifest_timestamps_only_is_churn(self):
        old = (b"installation:\n  version: 6.10.0\n"
               b"  lastUpdated: 2026-07-26T23:44:12.481Z\n"
               b"modules:\n  - name: core\n    version: 6.10.0\n"
               b"    lastUpdated: 2026-07-26T23:44:12.453Z\n")
        new = old.replace(b"2026-07-26T23:44:12.481Z", b"2026-08-08T04:44:37.186Z") \
                 .replace(b"2026-07-26T23:44:12.453Z", b"2026-08-08T04:44:37.167Z")
        self.assertEqual(
            bmadchurn.churn_class("_bmad/_config/manifest.yaml", old, new),
            "manifest-timestamps-only")

    def test_manifest_version_change_stays(self):
        old = b"modules:\n  - name: tea\n    version: v1.19.1\n    lastUpdated: A\n"
        new = b"modules:\n  - name: tea\n    version: v1.21.7\n    lastUpdated: B\n"
        self.assertIsNone(
            bmadchurn.churn_class("_bmad/_config/manifest.yaml", old, new))

    def test_reserialization_outside_config_files_stays(self):
        # the value-level equivalence is scoped: an ordinary yaml elsewhere
        # never gets the coercion treatment
        self.assertIsNone(
            bmadchurn.churn_class(".claude/skills/x/workflow.yaml",
                                    YAML_OLD, YAML_CHURN))

    def test_malformed_new_yaml_stays(self):
        self.assertIsNone(
            bmadchurn.churn_class("_bmad/gds/config.yaml", YAML_OLD,
                                    b"nested:\n  - broken\n misindent: [\n"))

    def test_scalar_type_change_stays(self):
        # review chip: Python cross-type equality (True == 1) must not make
        # a genuine yaml type change disappear — scalars compare type-strict
        old = b"debug: 1\nuser_name: Tim\n"
        new = b"debug: true\nuser_name: Tim\n"
        self.assertIsNone(
            bmadchurn.churn_class("_bmad/gds/config.yaml", old, new))

    def test_list_element_type_change_stays(self):
        old = b"flags:\n  - true\n"
        new = b"flags: '[1]'\n"
        self.assertIsNone(
            bmadchurn.churn_class("_bmad/gds/config.yaml", old, new))

    def test_comment_only_changes_are_churn_by_ruling(self):
        # pinned deliberately: the 2026-08-08 full-signature ruling ignores
        # ALL comment content in installer-generated config files, including
        # a regenerated `# Version:` header on a real core bump
        old = b"# Version: 6.10.0\nuser_name: Tim\n"
        new = b"# Version: 6.11.0\n# new upstream note\nuser_name: Tim\n"
        self.assertEqual(
            bmadchurn.churn_class("_bmad/gds/config.yaml", old, new),
            "config-values-unchanged")


class FilesManifestTestCase(unittest.TestCase):
    OLD = (b'type,name,module,path,hash\n'
           b'"yaml","manifest","_config","_config/manifest.yaml","aaa"\n'
           b'"md","SKILL","bmb","bmb/SKILL.md","bbb"\n')

    def test_hash_rows_of_reverted_files_are_derivative(self):
        new = self.OLD.replace(b'"aaa"', b'"ccc"')
        self.assertTrue(bmadchurn._files_manifest_derivative(
            self.OLD, new, {"_bmad/_config/manifest.yaml"}))

    def test_hash_row_of_unreverted_file_is_real(self):
        new = self.OLD.replace(b'"bbb"', b'"ccc"')
        self.assertFalse(bmadchurn._files_manifest_derivative(
            self.OLD, new, {"_bmad/_config/manifest.yaml"}))

    def test_added_or_removed_rows_are_real(self):
        new = self.OLD + b'"md","new","tea","tea/new.md","ddd"\n'
        self.assertFalse(bmadchurn._files_manifest_derivative(
            self.OLD, new, {"_bmad/_config/manifest.yaml"}))

    def test_non_hash_column_change_is_real(self):
        new = self.OLD.replace(b'"bmb/SKILL.md"', b'"bmb/OTHER.md"')
        self.assertFalse(bmadchurn._files_manifest_derivative(
            self.OLD, new, {"_bmad/bmb/SKILL.md", "_bmad/bmb/OTHER.md"}))


class NormalizeChurnTestCase(unittest.TestCase):
    """End-to-end over a real temp git repo: churn reverted, real kept."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.repo = Path(tmp.name)
        self._git("init", "-q")
        self._git("config", "core.autocrlf", "false")
        self._git("config", "user.email", "t@t")
        self._git("config", "user.name", "t")
        (self.repo / "_bmad" / "gds").mkdir(parents=True)
        (self.repo / "_bmad" / "scripts").mkdir()
        (self.repo / ".claude" / "skills" / "x").mkdir(parents=True)
        self.endings = self.repo / "_bmad" / "scripts" / "tool.py"
        self.config = self.repo / "_bmad" / "gds" / "config.yaml"
        self.real = self.repo / ".claude" / "skills" / "x" / "SKILL.md"
        self.endings.write_bytes(b"print('hi')\r\n")
        self.config.write_bytes(YAML_OLD)
        self.real.write_bytes(b"# skill\r\n")
        self._git("add", "-A")
        self._git("commit", "-q", "-m", "seed")

    def _git(self, *args):
        subprocess.run(["git", *args], cwd=str(self.repo), check=True,
                       stdin=subprocess.DEVNULL, capture_output=True)

    def test_normalize_reverts_churn_keeps_real_and_drops_baks(self):
        self.endings.write_bytes(b"print('hi')\n")                # churn
        self.config.write_bytes(YAML_CHURN)                       # churn
        self.real.write_bytes(b"# skill\nreal new content\n")     # real
        bak = self.config.with_suffix(".yaml.bak")
        bak.write_bytes(YAML_OLD.replace(b"\n", b"\r\n"))         # backup drop
        stray = self.repo / "_bmad" / "scripts" / "orphan.bak"
        stray.write_bytes(b"not a copy of anything committed\n")  # kept

        result = bmadchurn.normalize_churn(self.repo)

        self.assertEqual(result["reverted"], 2)
        self.assertEqual(result["backups_dropped"], 1)
        self.assertEqual(result["by_class"], {
            "line-endings-only": 1,
            "config-values-unchanged": 1,
            "installer-backup-dropped": 1,
        })
        self.assertEqual(result["remaining"], 2)  # the real change + the stray
        self.assertEqual(self.endings.read_bytes(), b"print('hi')\r\n")
        self.assertEqual(self.config.read_bytes(), YAML_OLD)
        self.assertIn(b"real new content", self.real.read_bytes())
        self.assertFalse(bak.exists())
        self.assertTrue(stray.exists())

        porcelain = subprocess.run(
            ["git", "status", "--porcelain"], cwd=str(self.repo),
            capture_output=True, encoding="utf-8").stdout
        dirty = sorted(line[3:] for line in porcelain.splitlines())
        self.assertEqual(dirty, sorted([".claude/skills/x/SKILL.md",
                                        "_bmad/scripts/orphan.bak"]))

    def test_preserved_paths_are_never_touched(self):
        # tk install snapshots what was dirty before the run: a user's
        # uncommitted edit and a pre-existing backup are not the install's
        # churn, even when they would classify as churn
        self.endings.write_bytes(b"print('hi')\n")                # dirty before
        bak = self.config.with_suffix(".yaml.bak")
        bak.write_bytes(YAML_OLD)                                 # dirty before
        preserve = bmadchurn.dirty_paths(self.repo)
        self.assertEqual(preserve, frozenset({"_bmad/scripts/tool.py",
                                              "_bmad/gds/config.yaml.bak"}))
        self.config.write_bytes(YAML_CHURN)                       # the install's churn

        result = bmadchurn.normalize_churn(self.repo, preserve)

        self.assertEqual(result["reverted"], 1)
        self.assertEqual(result["by_class"], {"config-values-unchanged": 1})
        self.assertEqual(result["remaining"], 0)  # preserved paths excluded
        self.assertEqual(self.endings.read_bytes(), b"print('hi')\n")
        self.assertTrue(bak.exists())
        self.assertEqual(self.config.read_bytes(), YAML_OLD)

    def test_clean_tree_normalizes_to_nothing(self):
        result = bmadchurn.normalize_churn(self.repo)
        self.assertEqual(result, {"reverted": 0, "backups_dropped": 0,
                                  "by_class": {}, "remaining": 0})


    def test_failed_checkout_writes_the_batch_back(self):
        # an IDE's background git can hold index.lock at the wrong moment:
        # the batch was already unlinked, so its bytes must be put back —
        # a stop never leaves tracked files deleted from the user's tree
        self.endings.write_bytes(b"print('hi')\n")
        self.config.write_bytes(YAML_CHURN)
        real_git = bmadchurn._git

        def flaky(directory, *args):
            if "checkout" in args:
                raise RuntimeError("git checkout failed: Unable to create index.lock")
            return real_git(directory, *args)

        with mock.patch.object(bmadchurn, "_git", side_effect=flaky):
            with self.assertRaisesRegex(RuntimeError, "index.lock"):
                bmadchurn.normalize_churn(self.repo)
        self.assertEqual(self.endings.read_bytes(), b"print('hi')\n")
        self.assertEqual(self.config.read_bytes(), YAML_CHURN)

    def test_glob_characters_in_paths_are_literal(self):
        # `[x].py` is a file name, not a pattern: a glob pathspec would also
        # match `x.py` and clobber its real change on checkout
        bracket = self.repo / "_bmad" / "scripts" / "[x].py"
        plain = self.repo / "_bmad" / "scripts" / "x.py"
        bracket.write_bytes(b"a = 1\r\n")
        plain.write_bytes(b"b = 1\r\n")
        self._git("add", "-A")
        self._git("commit", "-q", "-m", "bracketed name")
        bracket.write_bytes(b"a = 1\n")                           # churn
        plain.write_bytes(b"b = 2\r\n")                           # real

        result = bmadchurn.normalize_churn(self.repo)

        self.assertEqual(result["by_class"], {"line-endings-only": 1})
        self.assertEqual(bracket.read_bytes(), b"a = 1\r\n")
        self.assertEqual(plain.read_bytes(), b"b = 2\r\n")

    def test_status_parsing_handles_renames_and_untracked_files(self):
        # -z rename records carry the source path as a second NUL field, and
        # untracked files are listed one by one (a collapsed directory entry
        # would hide what an install adds inside it)
        self._git("mv", "_bmad/scripts/tool.py", "_bmad/scripts/renamed.py")
        extra = self.repo / ".claude" / "skills" / "new"
        extra.mkdir()
        (extra / "a.md").write_bytes(b"a\n")
        (extra / "b.md").write_bytes(b"b\n")

        self.assertEqual(bmadchurn.dirty_paths(self.repo), frozenset({
            "_bmad/scripts/renamed.py", "_bmad/scripts/tool.py",
            ".claude/skills/new/a.md", ".claude/skills/new/b.md",
        }))


class UnavailableReasonTestCase(unittest.TestCase):
    """Status paths are repo-root-relative and the churn classes name
    `_bmad/...` paths: only a project root that IS the git top-level, with
    `_bmad/` tracked, can be normalized; everything else says why, and
    nothing is touched."""

    def setUp(self):
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.base = Path(tmp.name)
        # never let discovery climb out of the sandbox into a real repo
        env = mock.patch.dict(os.environ, {"GIT_CEILING_DIRECTORIES": str(self.base)})
        env.start()
        self.addCleanup(env.stop)

    def _repo(self, *, track_bmad: bool) -> Path:
        repo = self.base / "repo"
        (repo / "project").mkdir(parents=True)
        for args in (["init", "-q"], ["config", "user.email", "t@t"],
                     ["config", "user.name", "t"]):
            subprocess.run(["git", *args], cwd=str(repo), check=True,
                           stdin=subprocess.DEVNULL, capture_output=True)
        if track_bmad:
            (repo / "_bmad").mkdir()
            (repo / "_bmad" / "config.toml").write_bytes(b"[core]\n")
            for args in (["add", "-A"], ["commit", "-q", "-m", "seed"]):
                subprocess.run(["git", *args], cwd=str(repo), check=True,
                               stdin=subprocess.DEVNULL, capture_output=True)
        return repo

    def test_git_top_level_with_tracked_bmad_is_normalizable(self):
        self.assertIsNone(bmadchurn.unavailable_reason(self._repo(track_bmad=True)))

    def test_untracked_bmad_is_not(self):
        # an ignored or never-committed _bmad/ shows nothing in git status:
        # normalizing would report a no-op no matter what the install wrote
        self.assertEqual(bmadchurn.unavailable_reason(self._repo(track_bmad=False)),
                         "_bmad/ is not tracked in git")

    def test_subdirectory_of_a_repo_is_not(self):
        repo = self._repo(track_bmad=True)
        self.assertEqual(bmadchurn.unavailable_reason(repo / "project"),
                         "project root is not the git top-level")

    def test_plain_directory_is_not(self):
        plain = self.base / "plain"
        plain.mkdir()
        self.assertEqual(bmadchurn.unavailable_reason(plain), "not a git work tree")

    def test_missing_directory_is_not(self):
        self.assertEqual(bmadchurn.unavailable_reason(self.base / "not-yet"),
                         "project root does not exist yet")


if __name__ == "__main__":
    unittest.main()
